### ISSUE TITLE
Instance Segmentation

### ISSUE THREAD

**Issue by sutiankang** [jahongir7174/YOLOv5-pt#1]
Thanks for sharing your repository. Can you expand further to instance segmentation task dut to this is difficult for me. Hope to get your reply.

**Comment by jahongir7174** [comment]
@sutiankang 
This repo supports detection only now, I can further upgrade later

**Comment by sutiankang** [comment]
> @sutiankang This repo supports detection only now, I can further upgrade later

Thank you for your reply.
