### ISSUE TITLE
Method to port weights from Ultralytics original repository

### ISSUE THREAD

**Issue by huynhthaihoa** [jahongir7174/YOLOv5-pt#4]
Hello @jahongir7174, thank you so much for your amazing work. I would like to ask about the method you used to port the weights from Ultralytics YOLOv5 repository. Could you please provide it here or any references to make it? Thanks again.

**Comment by jahongir7174** [comment]
Hello @huynhthaihoa 
```python
def port_weights(model1, model2):
    model1.eval()
    model2.eval()
    with torch.no_grad():
        m1_std = model1.state_dict().values()
        m2_std = model2.state_dict().values()
        for m1, m2 in zip(m1_std, m2_std):
            m1.copy_(m2)
    state = {'model': model1.half()}
    torch.save(state, f'weights/best_tf.pt')
```

model1 is the dst model
model2 is the src model

**Comment by huynhthaihoa** [comment]
Thank you so much brother, have a good day!
